In [6]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[6,5],[4,3]])
add=A+B
print("matrix addition: \n",add)
sub=A-B
print("matrix subtraction: \n",sub)
mul=A*B
print("matrix multiplication:\n",mul)
div=A/B
print("matrix division:\n",div)
dot_product=np.dot(A,B)
print("dot product:\n",dot_product)
transpose_A=A.T
print("Transpose of A:\n",transpose_A)
transpose_B=B.T
print("Transpose of B:\n",transpose_B)

matrix addition: 
 [[7 7]
 [7 7]]
matrix subtraction: 
 [[-5 -3]
 [-1  1]]
matrix multiplication:
 [[ 6 10]
 [12 12]]
matrix division:
 [[0.16666667 0.4       ]
 [0.75       1.33333333]]
dot product:
 [[14 11]
 [34 27]]
Transpose of A:
 [[1 3]
 [2 4]]
Transpose of B:
 [[6 4]
 [5 3]]
